### ISSUE TITLE
Problem with npm run build step on readme instructions. Missing config file?

### ISSUE THREAD

**Issue by SeadnaS** [Azure-Samples/communication-services-web-calling-wpf-sample#2]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Follow readme installation instructions to step 5. Fails on step 5.

### Any log messages given by the failure
C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp>npm run build

> ACSCallingSampleForWpf@1.0.0 build C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp
> webpack --mode development

C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^

Error: Cannot find module './config.json'
Require stack:
- C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\webpack.config.js
- C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\node_modules\webpack-cli\bin\utils\convert-argv.js
- C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\node_modules\webpack-cli\bin\cli.js
- C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\webpack.config.js:3:16)
    at Module._compile (C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\node_modules\yargs\yargs.js:576:18)
    at C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\seadn\Downloads\communication-services-web-calling-wpf-sample-main\communication-services-web-calling-wpf-sample-main\project\webapp\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\seadn\\Downloads\\communication-services-web-calling-wpf-sample-main\\communication-services-web-calling-wpf-sample-main\\project\\webapp\\webpack.config.js',
    'C:\\Users\\seadn\\Downloads\\communication-services-web-calling-wpf-sample-main\\communication-services-web-calling-wpf-sample-main\\project\\webapp\\node_modules\\webpack-cli\\bin\\utils\\convert-argv.js',
    'C:\\Users\\seadn\\Downloads\\communication-services-web-calling-wpf-sample-main\\communication-services-web-calling-wpf-sample-main\\project\\webapp\\node_modules\\webpack-cli\\bin\\cli.js',
    'C:\\Users\\seadn\\Downloads\\communication-services-web-calling-wpf-sample-main\\communication-services-web-calling-wpf-sample-main\\project\\webapp\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ACSCallingSampleForWpf@1.0.0 build: `webpack --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ACSCallingSampleForWpf@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\seadn\AppData\Roaming\npm-cache\_logs\2021-05-14T10_51_53_099Z-debug.log

### Expected/desired behavior
npm run build works and I can continue to next step

### OS and Version?
Windows 10 20H2 (19042.985)

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by SeadnaS** [comment]
I got it to build. I missed the step about creating the config.json initially. I created the config added my connection string and it built fine. However, I got a blank white screen when I run the app. So i reinstalled the webview2 nuget package, I then got errors when building saying that it could not find webview2. I reinstalled again with no luck. I updated to latest version of webview2 and it builds fine now but I still get white screen :( . I can open the localhost page in browser and it looks fine the webview just does not work however. 
![image](https://user-images.githubusercontent.com/67462486/118284910-de3e0f00-b4c8-11eb-9dca-190a416febda.png)
